INSERT INTO EMPRESA (NOME, PONTUACAO) VALUES('Empresa1', 50)
INSERT INTO EMPRESA (NOME, PONTUACAO) VALUES('Empresa2', 50)
INSERT INTO EMPRESA (NOME, PONTUACAO) VALUES('Empresa3', 50)
INSERT INTO EMPRESA (NOME, PONTUACAO) VALUES('Empresa4', 50)